### ISSUE TITLE
Configure Affinity and Tolerations for DB pods

### ISSUE THREAD

**Issue by nblxa** [GoogleCloudPlatform/elcarro-oracle-operator#268]
**Is your feature request related to a problem? Please describe.**
Oracle recommends adjusting Linux kernel parameters (https://docs.oracle.com/en/database/oracle/oracle-database/19/ladbi/changing-kernel-parameter-values.html#GUID-FB0CC366-61C9-4AA2-9BE7-233EB6810A31). Some of these are not namespaced, for instance, `fs.aio-max-nr`. The default value on GKE nodes (65536) is lower than the Oracle 
recommendation. Therefore it is necessary to control scheduling of Instance DB pods only on specifically prepared nodes with `affinity`.

In addition, `tolerations` are quite helpful for achieving workload separation.

**Describe the solution you'd like**
Parameters related to scheduling can be set on the Instance, and will be propagated by the operator to managed StatefulSets and possibly the Deployments as well.
Example:
```yaml
apiVersion: oracle.db.anthosapis.com/v1alpha1
kind: Instance
metadata:
  name: mydb
spec:
  cdbName: CDB
  cloudProvider: GCP
  databaseResources:
    requests:
      memory: 4.0Gi
  ...
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - oracle
  tolerations:
    - key: app
      value: oracle
      effect: NoSchedule
```

Alternatively only the `nodeAffinity` part of the `affinity` element may be supported.

**Describe alternatives you've considered**
1. Adjust kernel parameters on all nodes in the GKE cluster, which may cause conflicts.
2. Use a mutating admission controller to modify pods belonging to StatefulSets managed by El Carro. The downsize is the increased complexity.
