### ISSUE TITLE
Resizing of instances (CPU, RAM, Disks)

### ISSUE THREAD

**Issue by M-Schiefer** [GoogleCloudPlatform/elcarro-oracle-operator#278]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to resize an already deployed El Carro Instance. Changes made to databaseResources are not applied to the statefulset.

**Describe the solution you'd like**
When changing the resources of the instance described in:
```
  databaseResources:
    requests:
      memory: 64Gi
      cpu: 8
```
and/or the disk sizes described in:
```
  disks:
    - name: DataDisk
      size: 210Gi
      storageClass: "standard-rwo"
    - name: LogDisk
      size: 110Gi
      storageClass: "standard-rwo"
```
the Statefulset and PVCs should be resized accordingly. (+ whatever needs to happen inside Oracle to support this, apart from possibly necessary parameter changes that are under the responsibility of the user, e.g. sga_max_size)

**Describe alternatives you've considered**
Resizing the PVCs manually does work (Scale down statefulset -> Change PVC -> Scale up statefulset) and the disk space can be used by Oracle afterwards. Manually changing the Statefulset might work as well, but we weren't able to test it extensively for unexpected side-effects.

Thx for considering our request!
