### ISSUE TITLE
Specified size of additional disks on Instance is ignored

### ISSUE THREAD

**Issue by M-Schiefer** [GoogleCloudPlatform/elcarro-oracle-operator#371]
**Describe the bug**
When defining an additional disk in the Instance spec, e.g. like this:

```
  disks:
    - name: DataDisk
      size: 200Gi
      storageClass: "standard-rwo"
    - name: LogDisk
      size: 100Gi
      storageClass: "standard-rwo"
    - name: DataDisk2
      size: 64Ti
      storageClass: standard-rwo
```

The disk will get a default size of 100Gi instead of the desired disk size of e.g. 64Ti.

**Expected behavior**
The disk should be created with the specified size, the same way the size of the default disks can be specified.

**Proposed solution**
This is the change I did in our fork and it has fixed the problem in our tests.
![image](https://github.com/GoogleCloudPlatform/elcarro-oracle-operator/assets/18743875/272becda-6998-48ae-bb89-6fe53ae6926b)
=> Because the new disk does not exist in the defaultDiskSpecs, the default size of 100Gi is used instead of the specified size.

common/pkg/utils/utils.go
```
func FindDiskSize(diskSpec *commonv1alpha1.DiskSpec, configSpec *commonv1alpha1.ConfigSpec, defaultDiskSpecs map[string]commonv1alpha1.DiskSpec, defaultDiskSize resource.Quantity) resource.Quantity {
	spec, exists := defaultDiskSpecs[diskSpec.Name]

	if !diskSpec.Size.IsZero() {
		return diskSpec.Size
	}

	if configSpec != nil {
		for _, d := range configSpec.Disks {
			if d.Name == diskSpec.Name {
				if !d.Size.IsZero() {
					return d.Size
				}
				break
			}
		}
	}

	if exists {
		return spec.Size
	}
	return defaultDiskSize
}
```
