### ISSUE TITLE
Additional disks prevent patching the instance

### ISSUE THREAD

**Issue by nblxa** [GoogleCloudPlatform/elcarro-oracle-operator#373]
**Describe the bug**
If an instance spec contains additional disks, it cannot be patched by El Carro. The instance always goes into the `PatchingBackupFailure` state.

**To Reproduce**
1. Create an instance with an additional disk and Patching service enabled e.g.:
    ```yaml
    spec:
      disks:
      - name: DataDisk
        size: 500Gi
        storageClass: standard-rwo
      - name: LogDisk
        size: 150Gi
        storageClass: standard-rwo
      - name: data1
        size: 1Gi
        storageClass: standard-rwo
    services:
      Patching: true
    ```
3. Update the `spec.images.service` to a new image.
4. Watch instance state changes `kubectl get instances -w`
5. See it reach the `PatchingBackupFailure` state 

**Expected behavior**
The instance is patched successfully.

**Operator log**
```
E0326 20:22:37.849271       1 instance_controller.go:249] controllers/Instance "msg"="patchingStateMachine failed" "error"="VolumeSnapshot.snapshot.storage.k8s.io \"patching-backup-oracle-191520240326725970651-\" is invalid: [metadata.name: Invalid value: \"patching-backup-oracle-191520240326725970651-\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: \"patching-backup-oracle-191520240326725970651-\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]" "Instance"={"Namespace":"test1","Name":"myinstance"}
```
Apparently the issue is caused by `prePatchBackup` where the function `GetPVCNameAndMount` is used but `GetCustomPVCNameAndMount` is not.
